<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-02-14 at 00:32:22.
 */
class TripServiceTest extends PHPUnit_Framework_TestCase {

    /**
     * @var TripService
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new TripService;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers TripService::getTripsByUser
     * @todo   Implement testGetTripsByUser().
     */
    public function testGetTripsByUser() {
        // Remove the following lines when you implement this test.
        $this->fail(
                'This test has not been implemented yet.'
        );
    }

}
